import { mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import { pathToFileURL } from "node:url"

export async function syncPluginIntoFixture(input: { repoRoot: string }) {
  const sourcePluginPath = join(input.repoRoot, "src/oc-evolver.ts")
  const fixturePluginPath = join(
    input.repoRoot,
    "eval/fixtures/base/.opencode/plugins/oc-evolver.ts",
  )
  const pluginSourceUrl = pathToFileURL(sourcePluginPath).href
  const bridgeSource = [
    "// Generated by scripts/sync-plugin-into-fixture.ts",
    `export { OCEvolverPlugin as server } from ${JSON.stringify(pluginSourceUrl)}`,
    "",
  ].join("\n")

  await mkdir(join(input.repoRoot, "eval/fixtures/base/.opencode/plugins"), {
    recursive: true,
  })
  await writeFile(fixturePluginPath, bridgeSource)

  return {
    fixturePluginPath,
    pluginSourceUrl,
  }
}
